const mongoose = require('mongoose');

const projectSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  projectName: String,
  location: String,
  projectType: String,
  area: Number,
  floors: Number,
  wallHeight: Number,
  wallThickness: Number,
  slabThickness: Number,
  bricks: String,
  cement: String,
  flooring: String,
  roofing: String,
  paint: String,
  laborRegion: String,
  contractorType: String,
  skilledLabor: Boolean,
  waterTank: Boolean,
  rainHarvest: Boolean,
  electrical: Boolean,
  plumbing: Boolean,
  kitchen: Boolean,
  notes: String,
  brickCost: Number,
  cementCost: Number,
  flooringCost: Number,
  roofingCost: Number,
  paintCost: Number,
  laborCost: Number,
  contractorCost: Number,
  waterTankCost: Number,
  rainHarvestCost: Number,
  electricalCost: Number,
  plumbingCost: Number,
  totalCost: Number,
  date: { type: Date, default: Date.now },
}, { timestamps: true });

module.exports = mongoose.model('Project', projectSchema);